name: prueba_kubo
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.4
  mvc_pattern: ^8.1.2
  intl: ^0.17.0
  material_design_icons_flutter: ^5.0.6295
  shared_preferences: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/images/
